export const booksData = [
  {
    id: 1,
    title: "Practical Modern JavaScript",
    subtitle: "Dive into ES6 and the Future of JavaScript",
    author: "Nicolas Bevacqua",
    published: "2017-07-16T00:00:00.000Z",
    pages: 334,
    description:
      "To get the most out of modern JavaScript, you need learn the latest features of its parent specification, ECMAScript 6 (ES6). This book provides a highly practical look at ES6, without getting lost in the specification or its implementation details.",
    rating: "4",
    cost: "7.99",
    categories: "programming",
  },
  {
    id: 2,
    title: "Understanding ECMAScript 6",
    subtitle: "The Definitive Guide for JavaScript Developers",
    author: "Nicolas Bevacqua",
    published: "2016-09-03T00:00:00.000Z",
    pages: 352,
    description:
      "ECMAScript 6 represents the biggest update to the core of JavaScript in the history of the language. In Understanding ECMAScript 6, expert developer Nicholas C. Zakas provides a complete guide to the object types, syntax, and other exciting changes that ECMAScript 6 brings to JavaScript",
    rating: "5",
    cost: "8.33",
    categories: "programming",
  },
  {
    id: 3,
    title: "Eloquent JavaScript, Third Edition",
    subtitle: "A Modern Introduction to Programming",
    author: "Marijn Haverbeke",
    published: "2018-12-04T00:00:00.000Z",
    pages: 435,
    description:
      "JavaScript lies at the heart of almost every modern web application, from social apps like Twitter to browser-based game frameworks like Phaser and Babylon. Though simple for beginners to pick up and play with, JavaScript is a flexible, complex language that you can use to build full-scale applications.",
    rating: "4",
    cost: "11.2",
    categories: "programming",
  },
  {
    id: 4,
    title: "Clean Code: A Handbook of Agile Software Craftsmanship",
    author: "Robert C. Martin",
    published: "2008-08-11T00:00:00.000Z",
    pages: 464,
    description:
      "This book teaches software engineering principles and techniques for writing clean, maintainable code. It covers various aspects of code quality, such as naming, formatting, comments, functions, and classes.",
    rating: "4",
    cost: "12.99",
    categories: "programming",
  },
  {
    id: 5,
    title: "The Pragmatic Programmer: Your Journey to Mastery",
    author: "David Thomas",
    published: "1999-10-20T00:00:00.000Z",
    pages: 352,
    description:
      "This book offers advice on the craft of software development. It covers topics such as practical techniques, development methodologies, and tools for producing high-quality, maintainable code.",
    rating: "4",
    cost: "14.99",
    categories: "programming",
  },
  {
    id: 6,
    title:
      "Learning React: A Hands-On Guide to Building Web Applications Using React and Redux",
    author: "Marijn Haverbeke",
    published: "2018-08-28T00:00:00.000Z",
    pages: 288,
    description:
      "This book provides a comprehensive introduction to building web applications using React and Redux. It covers fundamental concepts, best practices, and real-world examples to help readers learn and master React.",
    rating: "4",
    cost: "11.99",
    categories: "programming",
  },
  {
    id: 7,
    title:
      "Cracking the Coding Interview: 189 Programming Questions and Solutions",
    author: "David Thomas",
    published: "2015-07-01T00:00:00.000Z",
    pages: 687,
    description:
      "This book is a comprehensive guide to preparing for coding interviews. It covers a wide range of topics, including data structures, algorithms, problem-solving techniques, and interview strategies.",
    rating: "5",
    cost: "19.99",
    categories: "programming",
  },
  {
    id: 8,
    title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    author: "Eric Gamma, Richard Helm, Ralph Johnson, John Vlissides",
    published: "1994-10-31T00:00:00.000Z",
    pages: 416,
    description:
      "This book introduces design patterns, which are reusable solutions to common software design problems. It covers various design patterns, their benefits, and how to implement them in object-oriented software.",
    rating: "3",
    cost: "15.99",
    categories: "software engineering",
  },
  {
    id: 9,
    title:
      "Python Crash Course: A Hands-On, Project-Based Introduction to Programming",
    author: "Eric Matthes",
    published: "2015-11-01T00:00:00.000Z",
    pages: 562,
    description:
      "This book provides a fast-paced, thorough introduction to Python programming. It covers basic to advanced concepts, with hands-on projects designed to reinforce learning and practical skills.",
    rating: "5",
    cost: "16.99",
    categories: "python",
  },
  {
    id: 10,
    title:
      "Data Science for Business: What You Need to Know about Data Mining and Data-Analytic Thinking",
    author: "Foster Provost, Tom Fawcett",
    published: "2013-07-27T00:00:00.000Z",
    pages: 414,
    description:
      "This book provides an introduction to data science from a business perspective. It covers fundamental concepts, techniques, and applications of data science for making informed business decisions.",
    rating: "3",
    cost: "21.99",
    categories: "programming",
  },
  {
    id: 11,
    title: "Deep Learning",
    subtitle: "A Practitioner's Approach",
    author: "Adams Gibson",
    published: "2017-08-03T00:00:00.000Z",
    pages: 536,
    description:
      "This book provides a comprehensive introduction to deep learning techniques and their practical applications. It covers deep neural networks, convolutional networks, recurrent networks, and more.",
    rating: "4",
    cost: "24.99",
    categories: "machine learning",
  },

  {
    id: 12,
    title: "The Hitchhiker's Guide to the Galaxy",
    subtitle: "",
    author: "Douglas Adams",
    published: "1979-10-12T00:00:00.000Z",
    pages: 192,
    description:
      "The Hitchhiker's Guide to the Galaxy is a comic science fiction series created by Douglas Adams. Originally a radio comedy broadcast on the BBC in 1978, it was later adapted to other formats, including stage shows, novels, comic books, a 1981 TV series, a 1984 video game, a 2005 feature film, and its 2008 sequel.",
    rating: "3",
    cost: "6.99",
    categories: "science fiction",
  },
  {
    id: 13,
    title: "The Lord of the Rings",
    subtitle: "",
    author: "J. R. R. Tolkien",
    published: "1954-07-29T00:00:00.000Z",
    pages: 1136,
    description:
      "The Lord of the Rings is an epic high-fantasy trilogy written by English philologist and University of Oxford professor J. R. R. Tolkien. The story began as a sequel to Tolkien's 1937 fantasy novel The Hobbit, but eventually developed into a much larger work written in stages between 1937 and 1949. Much of the story is set in Middle-earth, which Tolkien invented for The Hobbit and further developed for The Lord of the Rings.",
    rating: "5",
    cost: "12.99",
    categories: "fantasy",
  },
  {
    id: 14,
    title: "Pride and Prejudice",
    subtitle: "",
    author: "Jane Austen",
    published: "1813-01-28T00:00:00.000Z",
    pages: 224,
    description:
      "Pride and Prejudice is a novel of manners by Jane Austen, first published in 1813. The story follows the main character, Elizabeth Bennet, as she deals with issues of marriage, morals, and misconceptions in the English upper class society of the late 18th century. Elizabeth is the intelligent and quick-witted daughter of a country gentleman living near London. Mrs. Bennet is determined to marry her daughters off to rich men, and she sees the arrival of the wealthy and single Mr. Bingley in their neighborhood as a great opportunity.",
    rating: "5",
    cost: "4.99",
    categories: "romance",
  },
  {
    id: 15,
    title: "A Brief History of Time",
    subtitle: "From the Big Bang to Black Holes",
    author: "Stephen Hawking",
    published: "1988-03-20T00:00:00.000Z",
    pages: 212,
    description:
      "A Brief History of Time is a popular science book by English theoretical physicist Stephen Hawking. It was first published in 1988 and has since become a worldwide bestseller, with over 10 million copies sold. The book explores some of the most basic questions about the universe, such as the nature of space and time, the origin of the universe, and the possibility of black holes and time travel.",
    rating: "3",
    cost: "9.99",
    categories: "science",
  },
  {
    id: 16,
    title: "To Kill a Mockingbird",
    subtitle: "",
    author: "Harper Lee",
    published: "1960-07-11T00:00:00.000Z",
    pages: 324,
    rating: "3",
    cost: "7.88",
    description:
      "To Kill a Mockingbird is a novel by Harper Lee published in 1960. It has been considered an American classic since its publication.  The story is set in Maycomb, Alabama, during the midst of the Great Depression, and tells the story of a young girl named Scout Finch who learns about racism and prejudice in her town through the trial of a black man named Tom Robinson, who has been accused of raping a white woman.",
    categories: "science fiction",
  },
];
